default_language_version:
    python: python3
repos:
-   repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-print]
        args: ['--enable=T', '--max-line-length=120']
