# Generated by Django 4.0.3 on 2022-03-29 16:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('intern', 'Intern'), ('dev', 'Dev'), ('techlead', 'TechLead'), ('it', 'IT'), ('cto', 'CTO')], max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='management.company')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('equipment_type', models.CharField(choices=[('pc', 'PC'), ('screen', 'Screen')], max_length=6)),
                ('memory', models.IntegerField(null=True)),
                ('hard_disk_size', models.IntegerField(null=True)),
                ('size', models.IntegerField(null=True)),
                ('model', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('free', 'Free'), ('used', 'Used')], max_length=100)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to='management.employee')),
            ],
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('equipment_type', 'pc'), ('hard_disk_size__isnull', False), ('memory__isnull', False), ('size__isnull', True)), models.Q(('equipment_type', 'screen'), ('hard_disk_size__isnull', True), ('memory__isnull', True), ('size__isnull', False)), _connector='OR'), name='management_equipment_criteria_matches_equipment_type'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('name', 'surname'), name='unique_booking'),
        ),
    ]
